//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sampleApp.myDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cityTbl
    {
        public int cityID { get; set; }
        public Nullable<int> fkstateID { get; set; }
        public string cityName { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual stateTbl stateTbl { get; set; }
    }
}
