//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sampleApp.myDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myappdbEntities : DbContext
    {
        public myappdbEntities()
            : base("name=myappdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminTbl> adminTbls { get; set; }
        public virtual DbSet<cityTbl> cityTbls { get; set; }
        public virtual DbSet<countryTbl> countryTbls { get; set; }
        public virtual DbSet<stateTbl> stateTbls { get; set; }
    }
}
