//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sampleApp.myDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class stateTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public stateTbl()
        {
            this.cityTbls = new HashSet<cityTbl>();
        }
    
        public int stateID { get; set; }
        public Nullable<int> fkcountryID { get; set; }
        public string stateName { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cityTbl> cityTbls { get; set; }
        public virtual countryTbl countryTbl { get; set; }
    }
}
